trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.14.6'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- script :
    make build
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop